language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - libtool
script:
- ./private/autogen
- ./configure
- make
- ./test

# vim:ts=2 sts=2 sw=2 et
