#!/bin/sh
set -e -u -x
${LIBTOOLIZE:-libtoolize} -q -c
${ACLOCAL:-aclocal} -I m4 --install
${AUTOCONF:-autoconf}
for subdir in config build-aux
do
    build_aux="/usr/share/libtool/$subdir"
    [ -d "$build_aux" ] && break
done
for file in install-sh config.sub config.guess
do
    rm -f tools/$file
    cp "$build_aux/$file" .
done
