#!/bin/sh
set -e
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar'
export GZIP='-9n'
tmpdir=$(mktemp -d)
version=$(grep AC_INIT configure.ac | grep -E -o '[0-9][.][0-9.]+')
cwd=$(pwd)
target="$tmpdir/utf8regex-$version/"
hg archive "$target"
cd "$target"
set -x
"$cwd/private/autogen"
rm -rf autom4te.cache
rm -rf .hg*
cd ..
tar -czf "$cwd/utf8regex-$version.tar.gz" "utf8regex-$version"

# vim:ts=4 sw=4 et
