#!/bin/sh
set -e
export TAR_OPTIONS='--owner root --group root --mode a+rX'
export GZIP='-9n'
tmpdir=$(mktemp -d)
version=$(grep AC_INIT configure.ac | grep -E -o '[0-9][.][0-9.]+')
cwd=$(pwd)
target="$tmpdir/utf8regex-$version/"
hg archive --config 'ui.archivemeta=false' "$target"
cd "$target"
set -x
"$cwd/tools/autogen"
rm -Rf autom4te.cache
cd ..
tar -czf "$cwd/utf8regex-$version.tar.gz" "utf8regex-$version"

# vim:ts=2 sw=2 et
