#!/bin/sh
set -e
export TAR_OPTIONS='--owner root --group root --mode a+rX'
export GZIP='-9n'
tmpdir=$(mktemp -d)
version=$(grep AC_INIT configure.ac | grep -E -o '[0-9][.][0-9.]+')
cwd=$(pwd)
target="$tmpdir/utf8regex-$version/"
hg archive "$target"
cd "$target"
set -x
libtoolize -q -c
aclocal -I m4/
for file in install-sh config.guess config.sub
do
  cp "/usr/share/libtool/config/$file" .
done
autoconf
rm -Rf autom4te.cache
cd ..
tar -czf "$cwd/utf8regex-$version.tar.gz" "utf8regex-$version"

# vim:ts=2 sw=2 et
